### ISSUE TITLE
State, Validity and Canonicality should be explained

### ISSUE THREAD

**Issue by chanan-sack** [Trinkler/alexandria#1]
The reason for splitting the papers into these categories should be provided in the README.MD, it's unclear and will improve on the library readability.

**Comment by retotrinkler** [comment]
have a look at this https://hackmd.io/wku4-9c7SXSj36B8TIZptA (will be posted as a blog post to trinkler.sh soon).

WIP:
[State](https://hackmd.io/X4MmKGgVSROL5ZLaHK2MFQ)
[Validity](https://hackmd.io/kMtEkYFXRXeCTtivl96yLg)
[Canonicality](https://hackmd.io/BKBVLZ9MSz25WRGBdruk3A)

happy to hear any comments/feedback!

**Comment by retotrinkler** [comment]
idea is to write up a basic introduction on all the main parts of blockchain design and have it hosted eg as a jekyll page http://idratherbewriting.com/documentation-theme-jekyll/ https://github.com/tomjoht/documentation-theme-jekyll

if ur interested to set something like this up?

**Comment by jamesray1** [comment]
@retotrinkler, I added a paragraph to the canonicality section discussing distributed app frameworks that do not require universal consensus:

> By contrast, other distributed app frameworks exist that do not enforce a universal truth, and thus
do not require universal consensus, such as [Holochain](https://holochain.org), [Secure Scuttlebutt](https://www.scuttlebutt.nz/), and [Dat Protocol](https://www.datprotocol.com/). Unlike the latter two, Holochain can be used for economic transactions. This is achieved with mutual credit or repututational currencies (think current-sees that enable us to see and recognise value flows) rather than fiat currencies. Fiat currencies include cryptocurrencies, or blockchain fiat currencies and tokens. Fiat in Latin literally means ["let it be done"](https://www.merriam-webster.com/dictionary/fiat), and when used in the context of a fiat currency means a currency that is created (without existing prior to that) by an authority, e.g. a government or the actors in a blockchain network (e.g. miners for proof-of-work consensus or validators for proof-of-stake consensus). An advantage of this approach is that a distributed app can be infinitely scalable. A disadvantage may be that it requires more design, implementation and coordination to build a new economy founded on mutual and reputational credit, rather than fiat currencies.

I also added a link to the intro to the README: https://github.com/Trinkler/alexandria/pull/2, as I feel like it is helpful to read it before plunging into the papers, and at least as an interim measure before a site is deployed.
